services:
  redis:
    container_name: redis-leaderboard
    image: redis:latest
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass Test123
    ports:
      - '6382:6379'
  api:
      container_name: dabernasho
      build:
        context: ./src
        dockerfile: Dabernasho.Api/Dockerfile
      ports:
        - "5089:80"
      environment:
        - REDIS_ENDPOINT_URL=redis:6379,password=Test123
        - Configs:ResetScoreJob:Cron=0 0 12 ? * FRI *
      depends_on:
        - redis